server:
  port: 9999    

spring: 
  application:
    name: demoMongo

  data:  
    mongodb:
#      host: 43.200.241.170
#      port: 27017
#      authentication-database: admin
#      username: rios
#      password: rrdb5678
#      database: rios-mongo-test
#      isActive: true
      
      host: 127.0.0.1
      port: 27017
#      authentication-database: admin
#      username: root
#      password: 1219
      database: mongo-test
      isActive: true
      
      auto-index-creation: true # 몽고DB의 unique index 사용시 설정      
      
  jpa:
    hibernate:
      ddl-auto: none
#      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect    
    
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO